//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmr_beergrain
    {
        public int id { get; set; }
        public string name { get; set; }
        public string origin { get; set; }
        public int type { get; set; }
        public decimal color { get; set; }
        public decimal yield { get; set; }
        public decimal late_extract { get; set; }
        public decimal percent { get; set; }
        public int not_fermentable { get; set; }
        public decimal coarse_fine_diff { get; set; }
        public decimal moisture { get; set; }
        public decimal diastatic_power { get; set; }
        public decimal protein { get; set; }
        public decimal ibu_gal_per_lb { get; set; }
        public decimal add_after_boil { get; set; }
        public decimal recommend_mash { get; set; }
        public decimal max_in_batch { get; set; }
        public string notes { get; set; }
        public decimal boil_time { get; set; }
        public string convert_grain { get; set; }
    }
}
