//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmr_beerstyle
    {
        public int id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public decimal max_og { get; set; }
        public decimal min_og { get; set; }
        public decimal max_fg { get; set; }
        public decimal min_fg { get; set; }
        public decimal max_carb { get; set; }
        public decimal min_carb { get; set; }
        public decimal max_color { get; set; }
        public decimal min_color { get; set; }
        public decimal max_abv { get; set; }
        public decimal min_abv { get; set; }
        public decimal max_ibu { get; set; }
        public decimal min_ibu { get; set; }
    }
}
