//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBC.BuscaInsumo.Mvc.Areas.DoMyRecipe.Domain.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DoMyRecipeDataContextContainer : DbContext
    {
        public DoMyRecipeDataContextContainer()
            : base("name=DoMyRecipeDataContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dmr_beergrain> dmr_beergrain { get; set; }
        public DbSet<dmr_beerstyle> dmr_beerstyle { get; set; }
    }
}
